# Generated by Django 4.1 on 2023-06-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankPage", "0005_transaction_delete_signup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance", old_name="Balance", new_name="total_balance",
        ),
    ]
